In [1]:
import os

os.chdir(r"D:\business_analytics_project1")

print(os.getcwd())

D:\business_analytics_project1

In [2]:
import pandas as pd

# Load the datasets
parts = pd.read_csv("data/raw/parts_master.csv")
purchase_orders = pd.read_csv("data/processed/purchase_orders_processed.csv")
supplier_risk = pd.read_csv("data/processed/supplier_risk_assessment.csv")

# Inspect dimensions
print("PARTS MASTER")
print(parts.shape)
print(parts.columns.tolist())
print()

print("PURCHASE ORDERS")
print(purchase_orders.shape)
print(purchase_orders.columns.tolist())
print()

print("SUPPLIER RISK ASSESSMENT")
print(supplier_risk.shape)
print(supplier_risk.columns.tolist())

PARTS MASTER
(300, 9)
['part_id', 'part_family', 'criticality_class', 'unit_cost', 'lead_time_days', 'supplier_id_primary', 'supplier_risk_class', 'is_repairable', 'shelf_life_days']

PURCHASE ORDERS
(29666, 17)
['po_id', 'supplier_id', 'site_id', 'part_id', 'order_date', 'promised_date', 'receipt_date', 'ordered_qty', 'received_qty', 'delivery_delay_days', 'late_delivery', 'actual_lead_time_days', 'lead_time_days_x', 'lead_time_days_y', 'lead_time_days', 'lead_time_variance_days', 'otif']

SUPPLIER RISK ASSESSMENT
(40, 21)
['supplier_id', 'late_delivery_rate', 'delivery_reliability', 'avg_lead_time_variance', 'lead_time_std', 'lead_time_instability', 'quality_incident_rate_pct', 'critical_parts_supplied', 'critical_part_share', 'critical_exposure_index', 'total_order_quantity', 'order_quantity_share', 'delivery_risk_score', 'lead_time_risk_score', 'quality_risk_score', 'performance_risk_score', 'critical_exposure_score', 'order_volume_exposure_score', 'business_criticality_score', 'supplier_priority_score', 'risk_category']

In [3]:
# Inspect supplier-part relationships

print("Unique suppliers in parts master:")
print(parts["supplier_id_primary"].nunique())

print("\nUnique suppliers in purchase orders:")
print(purchase_orders["supplier_id"].nunique())

print("\nUnique parts in parts master:")
print(parts["part_id"].nunique())

print("\nUnique parts in purchase orders:")
print(purchase_orders["part_id"].nunique())

Unique suppliers in parts master:
40

Unique suppliers in purchase orders:
40

Unique parts in parts master:
300

Unique parts in purchase orders:
300

In [4]:
# Sample records to understand the actual structure

display(parts.head())
display(purchase_orders.head())
display(supplier_risk.head())

,part_id,part_family,criticality_class,unit_cost,lead_time_days,supplier_id_primary,supplier_risk_class,is_repairable,shelf_life_days
0,P00001,Electrical,B,2323.45,27,SUP004,Low,No,735.0
1,P00002,Cabin,C,670.84,31,SUP028,Low,No,NaN
2,P00003,Avionics,C,219.44,49,SUP040,Medium,Yes,NaN
3,P00004,Electrical,A,12488.80,33,SUP034,Low,No,NaN
4,P00005,Cabin,C,1319.96,63,SUP024,Medium,No,NaN

,po_id,supplier_id,site_id,part_id,order_date,promised_date,receipt_date,ordered_qty,received_qty,delivery_delay_days,late_delivery,actual_lead_time_days,lead_time_days_x,lead_time_days_y,lead_time_days,lead_time_variance_days,otif
0,PO000001,SUP004,SITE01,P00001,2022-05-02,2022-05-28,2022-05-29,16,16,1,1,27,27,27,27,0,0
1,PO000002,SUP004,SITE01,P00001,2022-07-04,2022-07-31,2022-08-02,5,5,2,1,29,27,27,27,2,0
2,PO000003,SUP004,SITE01,P00001,2022-10-17,2022-11-12,2022-11-16,5,5,4,1,30,27,27,27,3,0
3,PO000004,SUP004,SITE01,P00001,2023-02-06,2023-03-07,2023-03-09,3,3,2,1,31,27,27,27,4,0
4,PO000005,SUP004,SITE01,P00001,2023-04-03,2023-04-28,2023-04-29,5,5,1,1,26,27,27,27,-1,0

,supplier_id,late_delivery_rate,delivery_reliability,avg_lead_time_variance,lead_time_std,lead_time_instability,quality_incident_rate_pct,critical_parts_supplied,critical_part_share,critical_exposure_index,...,order_quantity_share,delivery_risk_score,lead_time_risk_score,quality_risk_score,performance_risk_score,critical_exposure_score,order_volume_exposure_score,business_criticality_score,supplier_priority_score,risk_category
0,SUP001,42.19,57.81,0.17,7.40,-0.486346,0.46,0,0.0,-0.903564,...,1.803317,22.5,30.0,10.0,21.250,21.25,27.5,23.75,22.250,Low
1,SUP002,71.82,28.18,2.34,10.91,1.593822,1.31,0,0.0,-0.903564,...,3.588920,95.0,97.5,55.0,85.625,21.25,82.5,45.75,69.675,Critical
2,SUP003,66.98,33.02,1.78,9.23,0.789666,0.95,0,0.0,-0.903564,...,2.198763,60.0,82.5,30.0,58.125,21.25,47.5,31.75,47.575,Medium
3,SUP004,43.50,56.50,0.32,6.82,-0.626619,0.91,0,0.0,-0.903564,...,2.002075,30.0,22.5,27.5,27.500,21.25,35.0,26.75,27.200,Low
4,SUP005,66.28,33.72,2.10,7.43,0.296122,0.23,3,0.5,1.654354,...,1.102142,55.0,72.5,2.5,46.250,92.50,10.0,59.50,51.550,High

In [5]:
# View suppliers ranked by final priority score

supplier_risk_ranked = supplier_risk.sort_values(
    "supplier_priority_score",
    ascending=False
)

display(
    supplier_risk_ranked[
        [
            "supplier_id",
            "supplier_priority_score",
            "risk_category",
            "performance_risk_score",
            "business_criticality_score"
        ]
    ]
)

,supplier_id,supplier_priority_score,risk_category,performance_risk_score,business_criticality_score
22,SUP023,80.2250,Critical,96.8750,55.25
32,SUP033,77.6250,Critical,96.8750,48.75
12,SUP013,75.1125,Critical,72.1875,79.50
38,SUP039,73.0750,Critical,85.6250,54.25
20,SUP021,71.6625,Critical,75.9375,65.25
13,SUP014,71.0125,Critical,72.1875,69.25
1,SUP002,69.6750,Critical,85.6250,45.75
26,SUP027,68.3500,Critical,78.7500,52.75
14,SUP015,67.2000,Critical,70.0000,63.00
23,SUP024,67.0750,Critical,80.6250,46.75
8,SUP009,66.8750,High,85.6250,38.75
39,SUP040,65.6875,High,67.8125,62.50
37,SUP038,64.8500,High,61.2500,70.25
5,SUP006,64.3125,High,74.6875,48.75
25,SUP026,64.1750,High,83.1250,35.75
17,SUP018,62.6625,High,68.4375,54.00
7,SUP008,56.3375,High,49.0625,67.25
33,SUP034,54.5750,High,55.6250,53.00
4,SUP005,51.5500,High,46.2500,59.50
35,SUP036,50.4500,High,23.7500,90.50
24,SUP025,48.0750,Medium,65.6250,21.75
2,SUP003,47.5750,Medium,58.1250,31.75
11,SUP012,46.8250,Medium,19.3750,88.00
29,SUP030,46.7750,Medium,20.6250,86.00
15,SUP016,45.0000,Medium,62.5000,18.75
36,SUP037,44.6500,Medium,36.2500,57.25
6,SUP007,41.8000,Medium,27.5000,63.25
30,SUP031,40.7500,Medium,38.7500,43.75
18,SUP019,40.7125,Medium,32.1875,53.50
34,SUP035,38.9250,Medium,24.3750,60.75
28,SUP029,36.9500,Low,28.7500,49.25
21,SUP022,36.3750,Low,38.1250,33.75
9,SUP010,34.2750,Low,20.6250,54.75
27,SUP028,34.0625,Low,15.9375,61.25
16,SUP017,30.8250,Low,16.8750,51.75
10,SUP011,28.6750,Low,30.6250,25.75
3,SUP004,27.2000,Low,27.5000,26.75
0,SUP001,22.2500,Low,21.2500,23.75
19,SUP020,19.9000,Low,20.0000,19.75
31,SUP032,15.9125,Low,14.6875,17.75

In [6]:
# Select suppliers that deserve disruption analysis

disruption_candidates = supplier_risk[
    supplier_risk["risk_category"].isin(["Critical", "High"])
].sort_values(
    "supplier_priority_score",
    ascending=False
)

display(
    disruption_candidates[
        [
            "supplier_id",
            "supplier_priority_score",
            "risk_category",
            "performance_risk_score",
            "business_criticality_score"
        ]
    ]
)

,supplier_id,supplier_priority_score,risk_category,performance_risk_score,business_criticality_score
22,SUP023,80.2250,Critical,96.8750,55.25
32,SUP033,77.6250,Critical,96.8750,48.75
12,SUP013,75.1125,Critical,72.1875,79.50
38,SUP039,73.0750,Critical,85.6250,54.25
20,SUP021,71.6625,Critical,75.9375,65.25
13,SUP014,71.0125,Critical,72.1875,69.25
1,SUP002,69.6750,Critical,85.6250,45.75
26,SUP027,68.3500,Critical,78.7500,52.75
14,SUP015,67.2000,Critical,70.0000,63.00
23,SUP024,67.0750,Critical,80.6250,46.75
8,SUP009,66.8750,High,85.6250,38.75
39,SUP040,65.6875,High,67.8125,62.50
37,SUP038,64.8500,High,61.2500,70.25
5,SUP006,64.3125,High,74.6875,48.75
25,SUP026,64.1750,High,83.1250,35.75
17,SUP018,62.6625,High,68.4375,54.00
7,SUP008,56.3375,High,49.0625,67.25
33,SUP034,54.5750,High,55.6250,53.00
4,SUP005,51.5500,High,46.2500,59.50
35,SUP036,50.4500,High,23.7500,90.50

In [7]:
print("Disruption candidates:")
print("Critical:", (disruption_candidates["risk_category"] == "Critical").sum())
print("High:", (disruption_candidates["risk_category"] == "High").sum())
print("Total:", len(disruption_candidates))

Disruption candidates:
Critical: 10
High: 10
Total: 20

In [8]:
# Map selected disruption candidates to the parts they have actually supplied

supplier_part_history = (
    purchase_orders[
        purchase_orders["supplier_id"].isin(
            disruption_candidates["supplier_id"]
        )
    ]
    .groupby(["supplier_id", "part_id"])
    .agg(
        total_orders=("po_id", "count"),
        total_order_quantity=("ordered_qty", "sum"),
        total_received_quantity=("received_qty", "sum")
    )
    .reset_index()
)

# Add part information
supplier_part_history = supplier_part_history.merge(
    parts[
        [
            "part_id",
            "part_family",
            "criticality_class",
            "unit_cost",
            "supplier_id_primary"
        ]
    ],
    on="part_id",
    how="left"
)

# Sort by supplier and criticality
supplier_part_history = supplier_part_history.sort_values(
    ["supplier_id", "criticality_class", "total_order_quantity"],
    ascending=[True, True, False]
)

display(supplier_part_history.head(20))

,supplier_id,part_id,total_orders,total_order_quantity,total_received_quantity,part_family,criticality_class,unit_cost,supplier_id_primary
1,SUP002,P00171,57,348,336,Structure,B,977.38,SUP002
3,SUP002,P00231,185,5591,5411,Cabin,C,628.39,SUP002
0,SUP002,P00006,193,5252,5114,Cabin,C,665.36,SUP002
5,SUP002,P00297,135,2213,2137,LandingGear,C,1258.51,SUP002
2,SUP002,P00191,125,1571,1497,LandingGear,C,1101.47,SUP002
4,SUP002,P00290,68,626,605,LandingGear,C,1164.96,SUP002
10,SUP005,P00233,82,647,622,Cabin,A,10397.09,SUP005
8,SUP005,P00183,52,235,233,Avionics,A,3080.58,SUP005
6,SUP005,P00145,32,117,116,Hydraulics,A,3608.96,SUP005
9,SUP005,P00212,144,2898,2736,Fasteners,C,1060.94,SUP005
7,SUP005,P00182,71,583,547,Engine,C,371.98,SUP005
11,SUP005,P00237,55,311,302,Structure,C,191.53,SUP005
15,SUP006,P00072,104,1062,1044,Fasteners,B,5776.32,SUP006
20,SUP006,P00270,94,843,801,Electrical,B,3295.81,SUP006
16,SUP006,P00076,89,798,754,Structure,B,1209.39,SUP006
17,SUP006,P00175,196,5004,4798,Cabin,C,906.57,SUP006
21,SUP006,P00298,168,3096,3008,Avionics,C,305.20,SUP006
13,SUP006,P00048,154,2722,2611,Fasteners,C,1384.03,SUP006
18,SUP006,P00178,133,2193,2113,Fasteners,C,839.09,SUP006
12,SUP006,P00031,87,805,782,Engine,C,472.16,SUP006

In [9]:
# Summarize the parts exposed under each supplier disruption

supplier_disruption_summary = (
    supplier_part_history
    .groupby("supplier_id")
    .agg(
        affected_parts=("part_id", "nunique"),
        critical_parts_affected=(
            "criticality_class",
            lambda x: (x == "A").sum()
        ),
        total_order_quantity_exposed=(
            "total_order_quantity",
            "sum"
        )
    )
    .reset_index()
)

# Add supplier risk information
supplier_disruption_summary = supplier_disruption_summary.merge(
    supplier_risk[
        [
            "supplier_id",
            "supplier_priority_score",
            "risk_category"
        ]
    ],
    on="supplier_id",
    how="left"
)

supplier_disruption_summary = supplier_disruption_summary.sort_values(
    "supplier_priority_score",
    ascending=False
)

display(supplier_disruption_summary)

,supplier_id,affected_parts,critical_parts_affected,total_order_quantity_exposed,supplier_priority_score,risk_category
10,SUP023,4,2,2607,80.2250,Critical
14,SUP033,7,1,8272,77.6250,Critical
5,SUP013,13,3,14293,75.1125,Critical
18,SUP039,4,2,2342,73.0750,Critical
9,SUP021,6,2,9353,71.6625,Critical
6,SUP014,9,2,13834,71.0125,Critical
0,SUP002,6,0,15601,69.6750,Critical
13,SUP027,11,0,23791,68.3500,Critical
7,SUP015,7,4,3536,67.2000,Critical
11,SUP024,6,0,16150,67.0750,Critical
4,SUP009,5,0,11741,66.8750,High
19,SUP040,11,1,16905,65.6875,High
17,SUP038,8,1,18714,64.8500,High
2,SUP006,10,0,16781,64.3125,High
12,SUP026,7,0,10582,64.1750,High
8,SUP018,6,1,8804,62.6625,High
3,SUP008,6,2,9797,56.3375,High
15,SUP034,7,2,6349,54.5750,High
1,SUP005,6,3,4791,51.5500,High
16,SUP036,8,4,15202,50.4500,High

In [10]:
# Find all suppliers that have historically supplied each affected part

part_supplier_history = (
    purchase_orders
    .groupby("part_id")
    .agg(
        supplier_count=("supplier_id", "nunique"),
        suppliers=("supplier_id", lambda x: sorted(x.unique()))
    )
    .reset_index()
)

# Attach this information to our disruption-level supplier-part data
supplier_part_alternatives = supplier_part_history.merge(
    part_supplier_history,
    on="part_id",
    how="left"
)

# A part is single-source if only one supplier has historically supplied it
supplier_part_alternatives["is_single_source"] = (
    supplier_part_alternatives["supplier_count"] == 1
)

display(
    supplier_part_alternatives[
        [
            "supplier_id",
            "part_id",
            "part_family",
            "criticality_class",
            "total_order_quantity",
            "supplier_count",
            "suppliers",
            "is_single_source"
        ]
    ].head(30)
)

,supplier_id,part_id,part_family,criticality_class,total_order_quantity,supplier_count,suppliers,is_single_source
0,SUP002,P00171,Structure,B,348,1,[SUP002],True
1,SUP002,P00231,Cabin,C,5591,1,[SUP002],True
2,SUP002,P00006,Cabin,C,5252,1,[SUP002],True
3,SUP002,P00297,LandingGear,C,2213,1,[SUP002],True
4,SUP002,P00191,LandingGear,C,1571,1,[SUP002],True
5,SUP002,P00290,LandingGear,C,626,1,[SUP002],True
6,SUP005,P00233,Cabin,A,647,1,[SUP005],True
7,SUP005,P00183,Avionics,A,235,1,[SUP005],True
8,SUP005,P00145,Hydraulics,A,117,1,[SUP005],True
9,SUP005,P00212,Fasteners,C,2898,1,[SUP005],True
10,SUP005,P00182,Engine,C,583,1,[SUP005],True
11,SUP005,P00237,Structure,C,311,1,[SUP005],True
12,SUP006,P00072,Fasteners,B,1062,1,[SUP006],True
13,SUP006,P00270,Electrical,B,843,1,[SUP006],True
14,SUP006,P00076,Structure,B,798,1,[SUP006],True
15,SUP006,P00175,Cabin,C,5004,1,[SUP006],True
16,SUP006,P00298,Avionics,C,3096,1,[SUP006],True
17,SUP006,P00048,Fasteners,C,2722,1,[SUP006],True
18,SUP006,P00178,Fasteners,C,2193,1,[SUP006],True
19,SUP006,P00031,Engine,C,805,1,[SUP006],True
20,SUP006,P00202,Engine,C,139,1,[SUP006],True
21,SUP006,P00053,Engine,C,119,1,[SUP006],True
22,SUP008,P00243,LandingGear,A,255,1,[SUP008],True
23,SUP008,P00062,Electrical,A,38,1,[SUP008],True
24,SUP008,P00115,Cabin,B,4444,1,[SUP008],True
25,SUP008,P00188,Fasteners,B,465,1,[SUP008],True
26,SUP008,P00216,Avionics,C,3055,1,[SUP008],True
27,SUP008,P00039,LandingGear,C,1540,1,[SUP008],True
28,SUP009,P00084,Avionics,B,2324,1,[SUP009],True
29,SUP009,P00162,LandingGear,B,1203,1,[SUP009],True

In [11]:
# Summarize alternative-supplier availability for each disruption scenario

alternative_supplier_summary = (
    supplier_part_alternatives
    .groupby("supplier_id")
    .agg(
        affected_parts=("part_id", "nunique"),
        parts_with_alternatives=(
            "is_single_source",
            lambda x: (~x).sum()
        ),
        single_source_parts=(
            "is_single_source",
            "sum"
        ),
        critical_single_source_parts=(
            "is_single_source",
            lambda x: (
                x[
                    supplier_part_alternatives.loc[x.index, "criticality_class"] == "A"
                ]
            ).sum()
        )
    )
    .reset_index()
)

# Add risk information
alternative_supplier_summary = alternative_supplier_summary.merge(
    supplier_risk[
        [
            "supplier_id",
            "supplier_priority_score",
            "risk_category"
        ]
    ],
    on="supplier_id",
    how="left"
)

alternative_supplier_summary = alternative_supplier_summary.sort_values(
    "supplier_priority_score",
    ascending=False
)

display(alternative_supplier_summary)

,supplier_id,affected_parts,parts_with_alternatives,single_source_parts,critical_single_source_parts,supplier_priority_score,risk_category
10,SUP023,4,0,4,2,80.2250,Critical
14,SUP033,7,0,7,1,77.6250,Critical
5,SUP013,13,0,13,3,75.1125,Critical
18,SUP039,4,0,4,2,73.0750,Critical
9,SUP021,6,0,6,2,71.6625,Critical
6,SUP014,9,0,9,2,71.0125,Critical
0,SUP002,6,0,6,0,69.6750,Critical
13,SUP027,11,0,11,0,68.3500,Critical
7,SUP015,7,0,7,4,67.2000,Critical
11,SUP024,6,0,6,0,67.0750,Critical
4,SUP009,5,0,5,0,66.8750,High
19,SUP040,11,0,11,1,65.6875,High
17,SUP038,8,0,8,1,64.8500,High
2,SUP006,10,0,10,0,64.3125,High
12,SUP026,7,0,7,0,64.1750,High
8,SUP018,6,0,6,1,62.6625,High
3,SUP008,6,0,6,2,56.3375,High
15,SUP034,7,0,7,2,54.5750,High
1,SUP005,6,0,6,3,51.5500,High
16,SUP036,8,0,8,4,50.4500,High

In [12]:
supply_chain_history = pd.read_csv(
    "data/raw/supply_chain_history.csv"
)

print("Supply Chain History shape:", supply_chain_history.shape)
print("\nColumns:")
print(supply_chain_history.columns.tolist())

display(supply_chain_history.head())

Supply Chain History shape: (280800, 11)

Columns:
['date', 'site_id', 'part_id', 'planned_maintenance', 'consumption_qty', 'on_hand_qty', 'backorder_qty', 'blocked_qty', 'forecast_qty', 'forecast_type', 'forecast_uplift_pct']

,date,site_id,part_id,planned_maintenance,consumption_qty,on_hand_qty,backorder_qty,blocked_qty,forecast_qty,forecast_type,forecast_uplift_pct
0,2022-01-03,SITE01,P00001,False,2,11,0,0,2,Baseline,0.000
1,2022-01-10,SITE01,P00001,True,4,14,0,0,3,Adjusted,-0.115
2,2022-01-17,SITE01,P00001,True,2,12,0,0,3,Baseline,0.000
3,2022-01-24,SITE01,P00001,False,0,12,0,0,2,Baseline,0.000
4,2022-01-31,SITE01,P00001,True,0,12,0,0,1,Adjusted,-0.110

In [13]:
print(
    "Date range:",
    supply_chain_history["date"].min(),
    "to",
    supply_chain_history["date"].max()
)

Date range: 2022-01-03 to 2024-12-23

In [14]:
# Aggregate operational exposure for parts affected by each disruption candidate

part_operational_exposure = (
    supply_chain_history
    .groupby("part_id")
    .agg(
        total_consumption=("consumption_qty", "sum"),
        avg_daily_consumption=("consumption_qty", "mean"),
        avg_on_hand=("on_hand_qty", "mean"),
        min_on_hand=("on_hand_qty", "min"),
        total_backorder=("backorder_qty", "sum"),
        max_backorder=("backorder_qty", "max"),
        total_blocked=("blocked_qty", "sum")
    )
    .reset_index()
)

# Attach operational information to affected supplier-part combinations
supplier_part_exposure = supplier_part_history.merge(
    part_operational_exposure,
    on="part_id",
    how="left"
)

# Add unit cost
supplier_part_exposure["procurement_value_exposed"] = (
    supplier_part_exposure["total_order_quantity"]
    * supplier_part_exposure["unit_cost"]
)

display(
    supplier_part_exposure[
        [
            "supplier_id",
            "part_id",
            "part_family",
            "criticality_class",
            "total_order_quantity",
            "unit_cost",
            "procurement_value_exposed",
            "total_consumption",
            "avg_daily_consumption",
            "avg_on_hand",
            "total_backorder",
            "total_blocked"
        ]
    ].head(20)
)

,supplier_id,part_id,part_family,criticality_class,total_order_quantity,unit_cost,procurement_value_exposed,total_consumption,avg_daily_consumption,avg_on_hand,total_backorder,total_blocked
0,SUP002,P00171,Structure,B,348,977.38,340128.24,1109,1.184829,23.622863,0,5
1,SUP002,P00231,Cabin,C,5591,628.39,3513328.49,5615,5.998932,137.659188,0,146
2,SUP002,P00006,Cabin,C,5252,665.36,3494470.72,5160,5.512821,117.321581,0,114
3,SUP002,P00297,LandingGear,C,2213,1258.51,2785082.63,2737,2.924145,42.440171,0,22
4,SUP002,P00191,LandingGear,C,1571,1101.47,1730409.37,2437,2.603632,43.419872,0,6
5,SUP002,P00290,LandingGear,C,626,1164.96,729264.96,1316,1.405983,21.074786,1,20
6,SUP005,P00233,Cabin,A,647,10397.09,6726917.23,1599,1.708333,46.271368,0,51
7,SUP005,P00183,Avionics,A,235,3080.58,723936.30,994,1.061966,22.475427,0,35
8,SUP005,P00145,Hydraulics,A,117,3608.96,422248.32,646,0.690171,14.750000,0,12
9,SUP005,P00212,Fasteners,C,2898,1060.94,3074604.12,3258,3.480769,51.761752,0,56
10,SUP005,P00182,Engine,C,583,371.98,216864.34,1400,1.495726,25.024573,0,26
11,SUP005,P00237,Structure,C,311,191.53,59565.83,1052,1.123932,13.262821,5,8
12,SUP006,P00072,Fasteners,B,1062,5776.32,6134451.84,2018,2.155983,43.027778,0,54
13,SUP006,P00270,Electrical,B,843,3295.81,2778367.83,1816,1.940171,33.009615,0,37
14,SUP006,P00076,Structure,B,798,1209.39,965093.22,1737,1.855769,30.980769,0,20
15,SUP006,P00175,Cabin,C,5004,906.57,4536476.28,5187,5.541667,103.688034,0,146
16,SUP006,P00298,Avionics,C,3096,305.20,944899.20,3473,3.710470,69.705128,0,156
17,SUP006,P00048,Fasteners,C,2722,1384.03,3767329.66,3128,3.341880,63.192308,0,82
18,SUP006,P00178,Fasteners,C,2193,839.09,1840124.37,2861,3.056624,52.065171,0,23
19,SUP006,P00031,Engine,C,805,472.16,380088.80,1698,1.814103,29.883547,0,39

In [16]:
# Add single-source information to the exposure dataset

supplier_part_exposure = supplier_part_exposure.merge(
    supplier_part_alternatives[
        [
            "supplier_id",
            "part_id",
            "is_single_source"
        ]
    ],
    on=["supplier_id", "part_id"],
    how="left"
)

print("Columns added successfully:")
print(
    supplier_part_exposure[
        ["supplier_id", "part_id", "is_single_source"]
    ].head()
)

Columns added successfully:
  supplier_id part_id  is_single_source
0      SUP002  P00171              True
1      SUP002  P00231              True
2      SUP002  P00006              True
3      SUP002  P00297              True
4      SUP002  P00191              True

In [17]:
# Aggregate part-level exposure into supplier disruption scenarios

disruption_scenario_summary = (
    supplier_part_exposure
    .groupby("supplier_id")
    .agg(
        affected_parts=("part_id", "nunique"),

        critical_parts_affected=(
            "criticality_class",
            lambda x: (x == "A").sum()
        ),

        total_order_quantity_exposed=(
            "total_order_quantity",
            "sum"
        ),

        critical_order_quantity_exposed=(
            "total_order_quantity",
            lambda x: x[
                supplier_part_exposure.loc[
                    x.index, "criticality_class"
                ] == "A"
            ].sum()
        ),

        procurement_value_exposed=(
            "procurement_value_exposed",
            "sum"
        ),

        critical_procurement_value_exposed=(
            "procurement_value_exposed",
            lambda x: x[
                supplier_part_exposure.loc[
                    x.index, "criticality_class"
                ] == "A"
            ].sum()
        ),

        total_consumption=(
            "total_consumption",
            "sum"
        ),

        average_daily_consumption=(
            "avg_daily_consumption",
            "sum"
        ),

        average_on_hand_inventory=(
            "avg_on_hand",
            "sum"
        ),

        total_backorder=(
            "total_backorder",
            "sum"
        ),

        total_blocked_quantity=(
            "total_blocked",
            "sum"
        ),

        single_source_parts=(
            "is_single_source",
            "sum"
        )
    )
    .reset_index()
)

# Add supplier risk information
disruption_scenario_summary = disruption_scenario_summary.merge(
    supplier_risk[
        [
            "supplier_id",
            "supplier_priority_score",
            "risk_category",
            "performance_risk_score",
            "business_criticality_score"
        ]
    ],
    on="supplier_id",
    how="left"
)

# Sort by supplier priority
disruption_scenario_summary = disruption_scenario_summary.sort_values(
    "supplier_priority_score",
    ascending=False
)

display(disruption_scenario_summary)

,supplier_id,affected_parts,critical_parts_affected,total_order_quantity_exposed,critical_order_quantity_exposed,procurement_value_exposed,critical_procurement_value_exposed,total_consumption,average_daily_consumption,average_on_hand_inventory,total_backorder,total_blocked_quantity,single_source_parts,supplier_priority_score,risk_category,performance_risk_score,business_criticality_score
10,SUP023,4,2,2607,750,4640540.32,4048573.44,5475,5.849359,116.270299,0,113,4,80.2250,Critical,96.8750,55.25
14,SUP033,7,1,8272,217,16590867.37,801287.69,12836,13.713675,494.267094,0,763,7,77.6250,Critical,96.8750,48.75
5,SUP013,13,3,14293,606,15020893.01,4216513.82,23144,24.726496,375.842949,26,396,13,75.1125,Critical,72.1875,79.50
18,SUP039,4,2,2342,1185,9882546.94,7790855.39,5958,6.365385,100.510684,29,63,4,73.0750,Critical,85.6250,54.25
9,SUP021,6,2,9353,521,14598403.06,3196500.10,12679,13.545940,268.882479,2,260,6,71.6625,Critical,75.9375,65.25
6,SUP014,9,2,13834,251,13304583.36,1645127.16,19165,20.475427,274.970085,5,247,9,71.0125,Critical,72.1875,69.25
0,SUP002,6,0,15601,0,12592684.41,0.00,18374,19.630342,385.538462,1,313,6,69.6750,Critical,85.6250,45.75
13,SUP027,11,0,23791,0,33795816.58,0.00,29235,31.233974,410.256410,38,604,11,68.3500,Critical,78.7500,52.75
7,SUP015,7,4,3536,579,5485655.31,3977652.20,7929,8.471154,117.084402,7,112,7,67.2000,Critical,70.0000,63.00
11,SUP024,6,0,16150,0,22738570.29,0.00,18772,20.055556,360.360043,0,350,6,67.0750,Critical,80.6250,46.75
4,SUP009,5,0,11741,0,8884349.40,0.00,14453,15.441239,242.125000,8,165,5,66.8750,High,85.6250,38.75
19,SUP040,11,1,16905,206,15768879.02,1662792.86,24427,26.097222,368.141026,20,390,11,65.6875,High,67.8125,62.50
17,SUP038,8,1,18714,103,31204412.22,559208.63,23489,25.095085,415.369658,0,274,8,64.8500,High,61.2500,70.25
2,SUP006,10,0,16781,0,21451420.65,0.00,23245,24.834402,453.087607,0,611,10,64.3125,High,74.6875,48.75
12,SUP026,7,0,10582,0,10712043.84,0.00,14494,15.485043,319.190171,0,320,7,64.1750,High,83.1250,35.75
8,SUP018,6,1,8804,294,6740532.53,438062.94,12548,13.405983,187.668803,19,214,6,62.6625,High,68.4375,54.00
3,SUP008,6,2,9797,293,23216159.32,5084413.50,13048,13.940171,123.623932,216,112,6,56.3375,High,49.0625,67.25
15,SUP034,7,2,6349,413,11953921.12,4706223.50,11493,12.278846,126.445513,65,158,7,54.5750,High,55.6250,53.00
1,SUP005,6,3,4791,999,11224136.14,7873101.85,8949,9.560897,173.545940,5,188,6,51.5500,High,46.2500,59.50
16,SUP036,8,4,15202,809,17481523.42,7051419.81,19053,20.355769,237.838675,23,237,8,50.4500,High,23.7500,90.50

In [18]:
# Business-facing disruption scenario table

disruption_business_view = disruption_scenario_summary[
    [
        "supplier_id",
        "risk_category",
        "supplier_priority_score",
        "affected_parts",
        "critical_parts_affected",
        "total_order_quantity_exposed",
        "critical_order_quantity_exposed",
        "procurement_value_exposed",
        "critical_procurement_value_exposed",
        "total_consumption",
        "average_on_hand_inventory",
        "total_backorder",
        "total_blocked_quantity",
        "single_source_parts"
    ]
].copy()

display(disruption_business_view)

,supplier_id,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,total_order_quantity_exposed,critical_order_quantity_exposed,procurement_value_exposed,critical_procurement_value_exposed,total_consumption,average_on_hand_inventory,total_backorder,total_blocked_quantity,single_source_parts
10,SUP023,Critical,80.2250,4,2,2607,750,4640540.32,4048573.44,5475,116.270299,0,113,4
14,SUP033,Critical,77.6250,7,1,8272,217,16590867.37,801287.69,12836,494.267094,0,763,7
5,SUP013,Critical,75.1125,13,3,14293,606,15020893.01,4216513.82,23144,375.842949,26,396,13
18,SUP039,Critical,73.0750,4,2,2342,1185,9882546.94,7790855.39,5958,100.510684,29,63,4
9,SUP021,Critical,71.6625,6,2,9353,521,14598403.06,3196500.10,12679,268.882479,2,260,6
6,SUP014,Critical,71.0125,9,2,13834,251,13304583.36,1645127.16,19165,274.970085,5,247,9
0,SUP002,Critical,69.6750,6,0,15601,0,12592684.41,0.00,18374,385.538462,1,313,6
13,SUP027,Critical,68.3500,11,0,23791,0,33795816.58,0.00,29235,410.256410,38,604,11
7,SUP015,Critical,67.2000,7,4,3536,579,5485655.31,3977652.20,7929,117.084402,7,112,7
11,SUP024,Critical,67.0750,6,0,16150,0,22738570.29,0.00,18772,360.360043,0,350,6
4,SUP009,High,66.8750,5,0,11741,0,8884349.40,0.00,14453,242.125000,8,165,5
19,SUP040,High,65.6875,11,1,16905,206,15768879.02,1662792.86,24427,368.141026,20,390,11
17,SUP038,High,64.8500,8,1,18714,103,31204412.22,559208.63,23489,415.369658,0,274,8
2,SUP006,High,64.3125,10,0,16781,0,21451420.65,0.00,23245,453.087607,0,611,10
12,SUP026,High,64.1750,7,0,10582,0,10712043.84,0.00,14494,319.190171,0,320,7
8,SUP018,High,62.6625,6,1,8804,294,6740532.53,438062.94,12548,187.668803,19,214,6
3,SUP008,High,56.3375,6,2,9797,293,23216159.32,5084413.50,13048,123.623932,216,112,6
15,SUP034,High,54.5750,7,2,6349,413,11953921.12,4706223.50,11493,126.445513,65,158,7
1,SUP005,High,51.5500,6,3,4791,999,11224136.14,7873101.85,8949,173.545940,5,188,6
16,SUP036,High,50.4500,8,4,15202,809,17481523.42,7051419.81,19053,237.838675,23,237,8

In [19]:
# Calculate network-level daily consumption for each disruption scenario

total_days = supply_chain_history["date"].nunique()

scenario_consumption = (
    supplier_part_exposure[
        ["supplier_id", "part_id"]
    ]
    .drop_duplicates()
    .merge(
        supply_chain_history[
            ["part_id", "date", "site_id", "consumption_qty"]
        ],
        on="part_id",
        how="left"
    )
    .groupby("supplier_id")
    .agg(
        total_consumption=("consumption_qty", "sum")
    )
    .reset_index()
)

scenario_consumption["average_daily_consumption"] = (
    scenario_consumption["total_consumption"] / total_days
)

print("Number of days in supply-chain history:", total_days)

display(scenario_consumption)

Number of days in supply-chain history: 156

   supplier_id  total_consumption  average_daily_consumption
0       SUP002              18374                 117.782051
1       SUP005               8949                  57.365385
2       SUP006              23245                 149.006410
3       SUP008              13048                  83.641026
4       SUP009              14453                  92.647436
5       SUP013              23144                 148.358974
6       SUP014              19165                 122.852564
7       SUP015               7929                  50.826923
8       SUP018              12548                  80.435897
9       SUP021              12679                  81.275641
10      SUP023               5475                  35.096154
11      SUP024              18772                 120.333333
12      SUP026              14494                  92.910256
13      SUP027              29235                 187.403846
14      SUP033              12836                  82.282051
15      SUP034              11493                  73.673077
16      SUP036              19053                 122.134615
17      SUP038              23489                 150.570513
18      SUP039               5958                  38.192308
19      SUP040              24427                 156.583333

In [20]:
# Replace the earlier daily-consumption calculation
disruption_scenario_summary = disruption_scenario_summary.drop(
    columns=["total_consumption", "average_daily_consumption"],
    errors="ignore"
)

disruption_scenario_summary = disruption_scenario_summary.merge(
    scenario_consumption,
    on="supplier_id",
    how="left"
)

disruption_scenario_summary = disruption_scenario_summary.sort_values(
    "supplier_priority_score",
    ascending=False
)

display(
    disruption_scenario_summary[
        [
            "supplier_id",
            "risk_category",
            "supplier_priority_score",
            "affected_parts",
            "critical_parts_affected",
            "total_order_quantity_exposed",
            "critical_order_quantity_exposed",
            "procurement_value_exposed",
            "critical_procurement_value_exposed",
            "total_consumption",
            "average_daily_consumption",
            "total_backorder",
            "total_blocked_quantity",
            "single_source_parts"
        ]
    ]
)

,supplier_id,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,total_order_quantity_exposed,critical_order_quantity_exposed,procurement_value_exposed,critical_procurement_value_exposed,total_consumption,average_daily_consumption,total_backorder,total_blocked_quantity,single_source_parts
0,SUP023,Critical,80.2250,4,2,2607,750,4640540.32,4048573.44,5475,35.096154,0,113,4
1,SUP033,Critical,77.6250,7,1,8272,217,16590867.37,801287.69,12836,82.282051,0,763,7
2,SUP013,Critical,75.1125,13,3,14293,606,15020893.01,4216513.82,23144,148.358974,26,396,13
3,SUP039,Critical,73.0750,4,2,2342,1185,9882546.94,7790855.39,5958,38.192308,29,63,4
4,SUP021,Critical,71.6625,6,2,9353,521,14598403.06,3196500.10,12679,81.275641,2,260,6
5,SUP014,Critical,71.0125,9,2,13834,251,13304583.36,1645127.16,19165,122.852564,5,247,9
6,SUP002,Critical,69.6750,6,0,15601,0,12592684.41,0.00,18374,117.782051,1,313,6
7,SUP027,Critical,68.3500,11,0,23791,0,33795816.58,0.00,29235,187.403846,38,604,11
8,SUP015,Critical,67.2000,7,4,3536,579,5485655.31,3977652.20,7929,50.826923,7,112,7
9,SUP024,Critical,67.0750,6,0,16150,0,22738570.29,0.00,18772,120.333333,0,350,6
10,SUP009,High,66.8750,5,0,11741,0,8884349.40,0.00,14453,92.647436,8,165,5
11,SUP040,High,65.6875,11,1,16905,206,15768879.02,1662792.86,24427,156.583333,20,390,11
12,SUP038,High,64.8500,8,1,18714,103,31204412.22,559208.63,23489,150.570513,0,274,8
13,SUP006,High,64.3125,10,0,16781,0,21451420.65,0.00,23245,149.006410,0,611,10
14,SUP026,High,64.1750,7,0,10582,0,10712043.84,0.00,14494,92.910256,0,320,7
15,SUP018,High,62.6625,6,1,8804,294,6740532.53,438062.94,12548,80.435897,19,214,6
16,SUP008,High,56.3375,6,2,9797,293,23216159.32,5084413.50,13048,83.641026,216,112,6
17,SUP034,High,54.5750,7,2,6349,413,11953921.12,4706223.50,11493,73.673077,65,158,7
18,SUP005,High,51.5500,6,3,4791,999,11224136.14,7873101.85,8949,57.365385,5,188,6
19,SUP036,High,50.4500,8,4,15202,809,17481523.42,7051419.81,19053,122.134615,23,237,8

In [21]:
# ============================================================
# DISRUPTION EXPOSURE RANKING
# ============================================================

exposure_ranking = disruption_scenario_summary[
    [
        "supplier_id",
        "risk_category",
        "supplier_priority_score",
        "affected_parts",
        "critical_parts_affected",
        "procurement_value_exposed",
        "critical_procurement_value_exposed",
        "average_daily_consumption",
        "total_backorder",
        "total_blocked_quantity"
    ]
].copy()

# Rank each disruption consequence.
# Higher exposure = better rank (Rank 1 = highest exposure)

exposure_ranking["rank_critical_parts"] = (
    exposure_ranking["critical_parts_affected"]
    .rank(method="min", ascending=False)
)

exposure_ranking["rank_critical_procurement"] = (
    exposure_ranking["critical_procurement_value_exposed"]
    .rank(method="min", ascending=False)
)

exposure_ranking["rank_procurement"] = (
    exposure_ranking["procurement_value_exposed"]
    .rank(method="min", ascending=False)
)

exposure_ranking["rank_daily_consumption"] = (
    exposure_ranking["average_daily_consumption"]
    .rank(method="min", ascending=False)
)

exposure_ranking["rank_backorder"] = (
    exposure_ranking["total_backorder"]
    .rank(method="min", ascending=False)
)

exposure_ranking["rank_blocked"] = (
    exposure_ranking["total_blocked_quantity"]
    .rank(method="min", ascending=False)
)

# Equal-weight rank aggregation
rank_columns = [
    "rank_critical_parts",
    "rank_critical_procurement",
    "rank_procurement",
    "rank_daily_consumption",
    "rank_backorder",
    "rank_blocked"
]

exposure_ranking["average_exposure_rank"] = (
    exposure_ranking[rank_columns].mean(axis=1)
)

# Rank the final disruption exposure
exposure_ranking["disruption_exposure_rank"] = (
    exposure_ranking["average_exposure_rank"]
    .rank(method="min", ascending=True)
    .astype(int)
)

# Final business view
disruption_exposure_ranking = exposure_ranking.sort_values(
    "disruption_exposure_rank"
)

display(
    disruption_exposure_ranking[
        [
            "disruption_exposure_rank",
            "supplier_id",
            "risk_category",
            "supplier_priority_score",
            "affected_parts",
            "critical_parts_affected",
            "procurement_value_exposed",
            "critical_procurement_value_exposed",
            "average_daily_consumption",
            "total_backorder",
            "total_blocked_quantity",
            "average_exposure_rank"
        ]
    ]
)

,disruption_exposure_rank,supplier_id,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,procurement_value_exposed,critical_procurement_value_exposed,average_daily_consumption,total_backorder,total_blocked_quantity,average_exposure_rank
2,1,SUP013,Critical,75.1125,13,3,15020893.01,4216513.82,148.358974,26,396,5.333333
19,2,SUP036,High,50.4500,8,4,17481523.42,7051419.81,122.134615,23,237,5.833333
7,3,SUP027,Critical,68.3500,11,0,33795816.58,0.00,187.403846,38,604,6.333333
11,4,SUP040,High,65.6875,11,1,15768879.02,1662792.86,156.583333,20,390,7.166667
16,4,SUP008,High,56.3375,6,2,23216159.32,5084413.50,83.641026,216,112,7.166667
12,6,SUP038,High,64.8500,8,1,31204412.22,559208.63,150.570513,0,274,8.833333
5,7,SUP014,Critical,71.0125,9,2,13304583.36,1645127.16,122.852564,5,247,9.166667
13,8,SUP006,High,64.3125,10,0,21451420.65,0.00,149.006410,0,611,9.333333
17,9,SUP034,High,54.5750,7,2,11953921.12,4706223.50,73.673077,65,158,9.500000
1,10,SUP033,Critical,77.6250,7,1,16590867.37,801287.69,82.282051,0,763,9.833333
18,11,SUP005,High,51.5500,6,3,11224136.14,7873101.85,57.365385,5,188,10.000000
4,12,SUP021,Critical,71.6625,6,2,14598403.06,3196500.10,81.275641,2,260,10.166667
9,13,SUP024,Critical,67.0750,6,0,22738570.29,0.00,120.333333,0,350,10.500000
3,14,SUP039,Critical,73.0750,4,2,9882546.94,7790855.39,38.192308,29,63,11.000000
6,15,SUP002,Critical,69.6750,6,0,12592684.41,0.00,117.782051,1,313,12.166667
8,16,SUP015,Critical,67.2000,7,4,5485655.31,3977652.20,50.826923,7,112,12.333333
14,17,SUP026,High,64.1750,7,0,10712043.84,0.00,92.910256,0,320,12.833333
15,18,SUP018,High,62.6625,6,1,6740532.53,438062.94,80.435897,19,214,13.166667
10,19,SUP009,High,66.8750,5,0,8884349.40,0.00,92.647436,8,165,13.666667
0,20,SUP023,Critical,80.2250,4,2,4640540.32,4048573.44,35.096154,0,113,14.000000

In [24]:
# ============================================================
# SAVE FINAL DISRUPTION SCENARIO ANALYSIS
# ============================================================

# Start from the complete scenario summary
final_disruption_output = disruption_scenario_summary.merge(
    exposure_ranking[
        [
            "supplier_id",
            "disruption_exposure_rank",
            "average_exposure_rank"
        ]
    ],
    on="supplier_id",
    how="left"
)

# Select the final business-facing columns
output_columns = [
    "disruption_exposure_rank",
    "supplier_id",
    "risk_category",
    "supplier_priority_score",
    "performance_risk_score",
    "business_criticality_score",
    "affected_parts",
    "critical_parts_affected",
    "total_order_quantity_exposed",
    "critical_order_quantity_exposed",
    "procurement_value_exposed",
    "critical_procurement_value_exposed",
    "total_consumption",
    "average_daily_consumption",
    "average_on_hand_inventory",
    "total_backorder",
    "total_blocked_quantity",
    "single_source_parts",
    "average_exposure_rank"
]

final_disruption_output = (
    final_disruption_output[output_columns]
    .sort_values("disruption_exposure_rank")
)

# Save final disruption scenario analysis
output_path = "data/processed/disruption_scenario_analysis.csv"

final_disruption_output.to_csv(
    output_path,
    index=False
)

print("Saved successfully:")
print(output_path)

display(final_disruption_output.head(10))

Saved successfully:
data/processed/disruption_scenario_analysis.csv

,disruption_exposure_rank,supplier_id,risk_category,supplier_priority_score,performance_risk_score,business_criticality_score,affected_parts,critical_parts_affected,total_order_quantity_exposed,critical_order_quantity_exposed,procurement_value_exposed,critical_procurement_value_exposed,total_consumption,average_daily_consumption,average_on_hand_inventory,total_backorder,total_blocked_quantity,single_source_parts,average_exposure_rank
2,1,SUP013,Critical,75.1125,72.1875,79.50,13,3,14293,606,15020893.01,4216513.82,23144,148.358974,375.842949,26,396,13,5.333333
19,2,SUP036,High,50.4500,23.7500,90.50,8,4,15202,809,17481523.42,7051419.81,19053,122.134615,237.838675,23,237,8,5.833333
7,3,SUP027,Critical,68.3500,78.7500,52.75,11,0,23791,0,33795816.58,0.00,29235,187.403846,410.256410,38,604,11,6.333333
11,4,SUP040,High,65.6875,67.8125,62.50,11,1,16905,206,15768879.02,1662792.86,24427,156.583333,368.141026,20,390,11,7.166667
16,4,SUP008,High,56.3375,49.0625,67.25,6,2,9797,293,23216159.32,5084413.50,13048,83.641026,123.623932,216,112,6,7.166667
12,6,SUP038,High,64.8500,61.2500,70.25,8,1,18714,103,31204412.22,559208.63,23489,150.570513,415.369658,0,274,8,8.833333
5,7,SUP014,Critical,71.0125,72.1875,69.25,9,2,13834,251,13304583.36,1645127.16,19165,122.852564,274.970085,5,247,9,9.166667
13,8,SUP006,High,64.3125,74.6875,48.75,10,0,16781,0,21451420.65,0.00,23245,149.006410,453.087607,0,611,10,9.333333
17,9,SUP034,High,54.5750,55.6250,53.00,7,2,6349,413,11953921.12,4706223.50,11493,73.673077,126.445513,65,158,7,9.500000
1,10,SUP033,Critical,77.6250,96.8750,48.75,7,1,8272,217,16590867.37,801287.69,12836,82.282051,494.267094,0,763,7,9.833333