In [1]:
import os

os.chdir(r"D:\business_analytics_project1")

print(os.getcwd())

D:\business_analytics_project1

In [2]:
import pandas as pd

# Load finalized disruption analysis
disruption = pd.read_csv(
    "data/processed/disruption_scenario_analysis.csv"
)

print("Shape:", disruption.shape)
print("\nColumns:")
print(disruption.columns.tolist())

display(disruption.head(10))

Shape: (20, 19)

Columns:
['disruption_exposure_rank', 'supplier_id', 'risk_category', 'supplier_priority_score', 'performance_risk_score', 'business_criticality_score', 'affected_parts', 'critical_parts_affected', 'total_order_quantity_exposed', 'critical_order_quantity_exposed', 'procurement_value_exposed', 'critical_procurement_value_exposed', 'total_consumption', 'average_daily_consumption', 'average_on_hand_inventory', 'total_backorder', 'total_blocked_quantity', 'single_source_parts', 'average_exposure_rank']

,disruption_exposure_rank,supplier_id,risk_category,supplier_priority_score,performance_risk_score,business_criticality_score,affected_parts,critical_parts_affected,total_order_quantity_exposed,critical_order_quantity_exposed,procurement_value_exposed,critical_procurement_value_exposed,total_consumption,average_daily_consumption,average_on_hand_inventory,total_backorder,total_blocked_quantity,single_source_parts,average_exposure_rank
0,1,SUP013,Critical,75.1125,72.1875,79.50,13,3,14293,606,15020893.01,4216513.82,23144,148.358974,375.842949,26,396,13,5.333333
1,2,SUP036,High,50.4500,23.7500,90.50,8,4,15202,809,17481523.42,7051419.81,19053,122.134615,237.838675,23,237,8,5.833333
2,3,SUP027,Critical,68.3500,78.7500,52.75,11,0,23791,0,33795816.58,0.00,29235,187.403846,410.256410,38,604,11,6.333333
3,4,SUP040,High,65.6875,67.8125,62.50,11,1,16905,206,15768879.02,1662792.86,24427,156.583333,368.141026,20,390,11,7.166667
4,4,SUP008,High,56.3375,49.0625,67.25,6,2,9797,293,23216159.32,5084413.50,13048,83.641026,123.623932,216,112,6,7.166667
5,6,SUP038,High,64.8500,61.2500,70.25,8,1,18714,103,31204412.22,559208.63,23489,150.570513,415.369658,0,274,8,8.833333
6,7,SUP014,Critical,71.0125,72.1875,69.25,9,2,13834,251,13304583.36,1645127.16,19165,122.852564,274.970085,5,247,9,9.166667
7,8,SUP006,High,64.3125,74.6875,48.75,10,0,16781,0,21451420.65,0.00,23245,149.006410,453.087607,0,611,10,9.333333
8,9,SUP034,High,54.5750,55.6250,53.00,7,2,6349,413,11953921.12,4706223.50,11493,73.673077,126.445513,65,158,7,9.500000
9,10,SUP033,Critical,77.6250,96.8750,48.75,7,1,8272,217,16590867.37,801287.69,12836,82.282051,494.267094,0,763,7,9.833333

In [3]:
# Focus on the most important disruption drivers

recommendation_view = disruption[
    [
        "disruption_exposure_rank",
        "supplier_id",
        "risk_category",
        "supplier_priority_score",
        "affected_parts",
        "critical_parts_affected",
        "total_order_quantity_exposed",
        "critical_order_quantity_exposed",
        "procurement_value_exposed",
        "critical_procurement_value_exposed",
        "average_daily_consumption",
        "total_backorder",
        "total_blocked_quantity",
        "single_source_parts"
    ]
].sort_values(
    "disruption_exposure_rank"
)

display(recommendation_view)

,disruption_exposure_rank,supplier_id,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,total_order_quantity_exposed,critical_order_quantity_exposed,procurement_value_exposed,critical_procurement_value_exposed,average_daily_consumption,total_backorder,total_blocked_quantity,single_source_parts
0,1,SUP013,Critical,75.1125,13,3,14293,606,15020893.01,4216513.82,148.358974,26,396,13
1,2,SUP036,High,50.4500,8,4,15202,809,17481523.42,7051419.81,122.134615,23,237,8
2,3,SUP027,Critical,68.3500,11,0,23791,0,33795816.58,0.00,187.403846,38,604,11
3,4,SUP040,High,65.6875,11,1,16905,206,15768879.02,1662792.86,156.583333,20,390,11
4,4,SUP008,High,56.3375,6,2,9797,293,23216159.32,5084413.50,83.641026,216,112,6
5,6,SUP038,High,64.8500,8,1,18714,103,31204412.22,559208.63,150.570513,0,274,8
6,7,SUP014,Critical,71.0125,9,2,13834,251,13304583.36,1645127.16,122.852564,5,247,9
7,8,SUP006,High,64.3125,10,0,16781,0,21451420.65,0.00,149.006410,0,611,10
8,9,SUP034,High,54.5750,7,2,6349,413,11953921.12,4706223.50,73.673077,65,158,7
9,10,SUP033,Critical,77.6250,7,1,8272,217,16590867.37,801287.69,82.282051,0,763,7
10,11,SUP005,High,51.5500,6,3,4791,999,11224136.14,7873101.85,57.365385,5,188,6
11,12,SUP021,Critical,71.6625,6,2,9353,521,14598403.06,3196500.10,81.275641,2,260,6
12,13,SUP024,Critical,67.0750,6,0,16150,0,22738570.29,0.00,120.333333,0,350,6
13,14,SUP039,Critical,73.0750,4,2,2342,1185,9882546.94,7790855.39,38.192308,29,63,4
14,15,SUP002,Critical,69.6750,6,0,15601,0,12592684.41,0.00,117.782051,1,313,6
15,16,SUP015,Critical,67.2000,7,4,3536,579,5485655.31,3977652.20,50.826923,7,112,7
16,17,SUP026,High,64.1750,7,0,10582,0,10712043.84,0.00,92.910256,0,320,7
17,18,SUP018,High,62.6625,6,1,8804,294,6740532.53,438062.94,80.435897,19,214,6
18,19,SUP009,High,66.8750,5,0,11741,0,8884349.40,0.00,92.647436,8,165,5
19,20,SUP023,Critical,80.2250,4,2,2607,750,4640540.32,4048573.44,35.096154,0,113,4

In [4]:
# ============================================================
# RECOMMENDATION DRIVERS
# ============================================================

recommendation_drivers = disruption.copy()

# Data-driven thresholds
critical_parts_threshold = recommendation_drivers[
    "critical_parts_affected"
].quantile(0.75)

procurement_threshold = recommendation_drivers[
    "procurement_value_exposed"
].quantile(0.75)

consumption_threshold = recommendation_drivers[
    "average_daily_consumption"
].quantile(0.75)

blocked_threshold = recommendation_drivers[
    "total_blocked_quantity"
].quantile(0.75)

backorder_threshold = recommendation_drivers[
    "total_backorder"
].quantile(0.75)

print("Data-driven thresholds:")
print("Critical parts:", critical_parts_threshold)
print("Procurement exposure:", procurement_threshold)
print("Daily consumption:", consumption_threshold)
print("Blocked quantity:", blocked_threshold)
print("Backorder:", backorder_threshold)

Data-driven thresholds:
Critical parts: 2.0
Procurement exposure: 18473997.7275
Daily consumption: 129.22916666666666
Blocked quantity: 360.0
Backorder: 23.75

In [5]:
# ============================================================
# FLAG THE MAIN DISRUPTION DRIVERS
# ============================================================

recommendation_drivers["critical_part_exposure"] = (
    recommendation_drivers["critical_parts_affected"]
    >= critical_parts_threshold
)

recommendation_drivers["high_procurement_exposure"] = (
    recommendation_drivers["procurement_value_exposed"]
    >= procurement_threshold
)

recommendation_drivers["high_consumption_exposure"] = (
    recommendation_drivers["average_daily_consumption"]
    >= consumption_threshold
)

recommendation_drivers["high_blocked_quantity"] = (
    recommendation_drivers["total_blocked_quantity"]
    >= blocked_threshold
)

recommendation_drivers["high_backorder"] = (
    recommendation_drivers["total_backorder"]
    >= backorder_threshold
)

recommendation_drivers["high_disruption_exposure"] = (
    recommendation_drivers["disruption_exposure_rank"] <= 5
)

recommendation_drivers["high_supplier_risk"] = (
    recommendation_drivers["risk_category"] == "Critical"
)

In [6]:
recommendation_flags = recommendation_drivers[
    [
        "supplier_id",
        "disruption_exposure_rank",
        "risk_category",
        "supplier_priority_score",
        "critical_parts_affected",
        "procurement_value_exposed",
        "average_daily_consumption",
        "total_backorder",
        "total_blocked_quantity",
        "single_source_parts",
        "critical_part_exposure",
        "high_procurement_exposure",
        "high_consumption_exposure",
        "high_blocked_quantity",
        "high_backorder",
        "high_disruption_exposure",
        "high_supplier_risk"
    ]
].sort_values(
    "disruption_exposure_rank"
)

display(recommendation_flags)

,supplier_id,disruption_exposure_rank,risk_category,supplier_priority_score,critical_parts_affected,procurement_value_exposed,average_daily_consumption,total_backorder,total_blocked_quantity,single_source_parts,critical_part_exposure,high_procurement_exposure,high_consumption_exposure,high_blocked_quantity,high_backorder,high_disruption_exposure,high_supplier_risk
0,SUP013,1,Critical,75.1125,3,15020893.01,148.358974,26,396,13,True,False,True,True,True,True,True
1,SUP036,2,High,50.4500,4,17481523.42,122.134615,23,237,8,True,False,False,False,False,True,False
2,SUP027,3,Critical,68.3500,0,33795816.58,187.403846,38,604,11,False,True,True,True,True,True,True
3,SUP040,4,High,65.6875,1,15768879.02,156.583333,20,390,11,False,False,True,True,False,True,False
4,SUP008,4,High,56.3375,2,23216159.32,83.641026,216,112,6,True,True,False,False,True,True,False
5,SUP038,6,High,64.8500,1,31204412.22,150.570513,0,274,8,False,True,True,False,False,False,False
6,SUP014,7,Critical,71.0125,2,13304583.36,122.852564,5,247,9,True,False,False,False,False,False,True
7,SUP006,8,High,64.3125,0,21451420.65,149.006410,0,611,10,False,True,True,True,False,False,False
8,SUP034,9,High,54.5750,2,11953921.12,73.673077,65,158,7,True,False,False,False,True,False,False
9,SUP033,10,Critical,77.6250,1,16590867.37,82.282051,0,763,7,False,False,False,True,False,False,True
10,SUP005,11,High,51.5500,3,11224136.14,57.365385,5,188,6,True,False,False,False,False,False,False
11,SUP021,12,Critical,71.6625,2,14598403.06,81.275641,2,260,6,True,False,False,False,False,False,True
12,SUP024,13,Critical,67.0750,0,22738570.29,120.333333,0,350,6,False,True,False,False,False,False,True
13,SUP039,14,Critical,73.0750,2,9882546.94,38.192308,29,63,4,True,False,False,False,True,False,True
14,SUP002,15,Critical,69.6750,0,12592684.41,117.782051,1,313,6,False,False,False,False,False,False,True
15,SUP015,16,Critical,67.2000,4,5485655.31,50.826923,7,112,7,True,False,False,False,False,False,True
16,SUP026,17,High,64.1750,0,10712043.84,92.910256,0,320,7,False,False,False,False,False,False,False
17,SUP018,18,High,62.6625,1,6740532.53,80.435897,19,214,6,False,False,False,False,False,False,False
18,SUP009,19,High,66.8750,0,8884349.40,92.647436,8,165,5,False,False,False,False,False,False,False
19,SUP023,20,Critical,80.2250,2,4640540.32,35.096154,0,113,4,True,False,False,False,False,False,True

In [7]:
# ============================================================
# SUPPLIER-SPECIFIC RECOMMENDATIONS
# ============================================================

def generate_recommendation(row):

    # Highest priority: critical parts + major disruption exposure
    if (
        row["high_disruption_exposure"]
        and row["critical_part_exposure"]
    ):
        return (
            "Immediate alternate-source qualification for critical parts",
            "Immediate",
            "High disruption exposure combined with multiple critical parts and single-source dependence."
        )

    # Critical parts even when overall disruption rank is lower
    elif row["critical_part_exposure"]:
        return (
            "Qualify alternate suppliers for critical parts",
            "High",
            "Multiple critical parts are exposed and the affected parts are single-source."
        )

    # Large operational demand exposure
    elif (
        row["high_disruption_exposure"]
        and row["high_consumption_exposure"]
    ):
        return (
            "Develop inventory and supply continuity contingency plan",
            "High",
            "High disruption exposure coincides with high daily consumption."
        )

    # Significant blocked quantity / backorders
    elif (
        row["high_blocked_quantity"]
        or row["high_backorder"]
    ):
        return (
            "Initiate supplier corrective action and operational recovery review",
            "High",
            "Elevated blocked quantity or backorder exposure indicates operational disruption."
        )

    # Large procurement exposure
    elif row["high_procurement_exposure"]:
        return (
            "Review procurement concentration and supply continuity options",
            "Medium",
            "High procurement value is exposed if the supplier becomes unavailable."
        )

    # High supplier risk but relatively low disruption consequence
    elif row["high_supplier_risk"]:
        return (
            "Enhanced supplier monitoring and periodic risk review",
            "Medium",
            "Supplier is classified as Critical risk, although disruption exposure is comparatively lower."
        )

    else:
        return (
            "Routine supplier monitoring",
            "Low",
            "No dominant disruption driver identified relative to the other suppliers."
        )


# Apply recommendation logic
recommendation_results = (
    recommendation_drivers.apply(
        generate_recommendation,
        axis=1,
        result_type="expand"
    )
)

recommendation_results.columns = [
    "recommended_action",
    "recommendation_urgency",
    "recommendation_rationale"
]

# Attach recommendations
supplier_recommendations = pd.concat(
    [
        recommendation_drivers.reset_index(drop=True),
        recommendation_results.reset_index(drop=True)
    ],
    axis=1
)

# Final business-facing table
supplier_recommendations = supplier_recommendations[
    [
        "supplier_id",
        "disruption_exposure_rank",
        "risk_category",
        "supplier_priority_score",
        "affected_parts",
        "critical_parts_affected",
        "single_source_parts",
        "procurement_value_exposed",
        "critical_procurement_value_exposed",
        "average_daily_consumption",
        "total_backorder",
        "total_blocked_quantity",
        "recommended_action",
        "recommendation_urgency",
        "recommendation_rationale"
    ]
].sort_values(
    "disruption_exposure_rank"
)

display(supplier_recommendations)

,supplier_id,disruption_exposure_rank,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,single_source_parts,procurement_value_exposed,critical_procurement_value_exposed,average_daily_consumption,total_backorder,total_blocked_quantity,recommended_action,recommendation_urgency,recommendation_rationale
0,SUP013,1,Critical,75.1125,13,3,13,15020893.01,4216513.82,148.358974,26,396,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
1,SUP036,2,High,50.4500,8,4,8,17481523.42,7051419.81,122.134615,23,237,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
2,SUP027,3,Critical,68.3500,11,0,11,33795816.58,0.00,187.403846,38,604,Develop inventory and supply continuity contin...,High,High disruption exposure coincides with high d...
3,SUP040,4,High,65.6875,11,1,11,15768879.02,1662792.86,156.583333,20,390,Develop inventory and supply continuity contin...,High,High disruption exposure coincides with high d...
4,SUP008,4,High,56.3375,6,2,6,23216159.32,5084413.50,83.641026,216,112,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
5,SUP038,6,High,64.8500,8,1,8,31204412.22,559208.63,150.570513,0,274,Review procurement concentration and supply co...,Medium,High procurement value is exposed if the suppl...
6,SUP014,7,Critical,71.0125,9,2,9,13304583.36,1645127.16,122.852564,5,247,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
7,SUP006,8,High,64.3125,10,0,10,21451420.65,0.00,149.006410,0,611,Initiate supplier corrective action and operat...,High,Elevated blocked quantity or backorder exposur...
8,SUP034,9,High,54.5750,7,2,7,11953921.12,4706223.50,73.673077,65,158,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
9,SUP033,10,Critical,77.6250,7,1,7,16590867.37,801287.69,82.282051,0,763,Initiate supplier corrective action and operat...,High,Elevated blocked quantity or backorder exposur...
10,SUP005,11,High,51.5500,6,3,6,11224136.14,7873101.85,57.365385,5,188,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
11,SUP021,12,Critical,71.6625,6,2,6,14598403.06,3196500.10,81.275641,2,260,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
12,SUP024,13,Critical,67.0750,6,0,6,22738570.29,0.00,120.333333,0,350,Review procurement concentration and supply co...,Medium,High procurement value is exposed if the suppl...
13,SUP039,14,Critical,73.0750,4,2,4,9882546.94,7790855.39,38.192308,29,63,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
14,SUP002,15,Critical,69.6750,6,0,6,12592684.41,0.00,117.782051,1,313,Enhanced supplier monitoring and periodic risk...,Medium,"Supplier is classified as Critical risk, altho..."
15,SUP015,16,Critical,67.2000,7,4,7,5485655.31,3977652.20,50.826923,7,112,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
16,SUP026,17,High,64.1750,7,0,7,10712043.84,0.00,92.910256,0,320,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
17,SUP018,18,High,62.6625,6,1,6,6740532.53,438062.94,80.435897,19,214,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
18,SUP009,19,High,66.8750,5,0,5,8884349.40,0.00,92.647436,8,165,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
19,SUP023,20,Critical,80.2250,4,2,4,4640540.32,4048573.44,35.096154,0,113,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...

In [8]:
# ============================================================
# SAVE FINAL SUPPLIER RECOMMENDATIONS
# ============================================================

recommendation_output = supplier_recommendations.copy()

output_path = "data/processed/supplier_recommendations.csv"

recommendation_output.to_csv(
    output_path,
    index=False
)

print("Saved successfully:")
print(output_path)

print("\nFinal recommendation table shape:")
print(recommendation_output.shape)

display(recommendation_output)

Saved successfully:
data/processed/supplier_recommendations.csv

Final recommendation table shape:
(20, 15)

,supplier_id,disruption_exposure_rank,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,single_source_parts,procurement_value_exposed,critical_procurement_value_exposed,average_daily_consumption,total_backorder,total_blocked_quantity,recommended_action,recommendation_urgency,recommendation_rationale
0,SUP013,1,Critical,75.1125,13,3,13,15020893.01,4216513.82,148.358974,26,396,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
1,SUP036,2,High,50.4500,8,4,8,17481523.42,7051419.81,122.134615,23,237,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
2,SUP027,3,Critical,68.3500,11,0,11,33795816.58,0.00,187.403846,38,604,Develop inventory and supply continuity contin...,High,High disruption exposure coincides with high d...
3,SUP040,4,High,65.6875,11,1,11,15768879.02,1662792.86,156.583333,20,390,Develop inventory and supply continuity contin...,High,High disruption exposure coincides with high d...
4,SUP008,4,High,56.3375,6,2,6,23216159.32,5084413.50,83.641026,216,112,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
5,SUP038,6,High,64.8500,8,1,8,31204412.22,559208.63,150.570513,0,274,Review procurement concentration and supply co...,Medium,High procurement value is exposed if the suppl...
6,SUP014,7,Critical,71.0125,9,2,9,13304583.36,1645127.16,122.852564,5,247,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
7,SUP006,8,High,64.3125,10,0,10,21451420.65,0.00,149.006410,0,611,Initiate supplier corrective action and operat...,High,Elevated blocked quantity or backorder exposur...
8,SUP034,9,High,54.5750,7,2,7,11953921.12,4706223.50,73.673077,65,158,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
9,SUP033,10,Critical,77.6250,7,1,7,16590867.37,801287.69,82.282051,0,763,Initiate supplier corrective action and operat...,High,Elevated blocked quantity or backorder exposur...
10,SUP005,11,High,51.5500,6,3,6,11224136.14,7873101.85,57.365385,5,188,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
11,SUP021,12,Critical,71.6625,6,2,6,14598403.06,3196500.10,81.275641,2,260,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
12,SUP024,13,Critical,67.0750,6,0,6,22738570.29,0.00,120.333333,0,350,Review procurement concentration and supply co...,Medium,High procurement value is exposed if the suppl...
13,SUP039,14,Critical,73.0750,4,2,4,9882546.94,7790855.39,38.192308,29,63,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
14,SUP002,15,Critical,69.6750,6,0,6,12592684.41,0.00,117.782051,1,313,Enhanced supplier monitoring and periodic risk...,Medium,"Supplier is classified as Critical risk, altho..."
15,SUP015,16,Critical,67.2000,7,4,7,5485655.31,3977652.20,50.826923,7,112,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
16,SUP026,17,High,64.1750,7,0,7,10712043.84,0.00,92.910256,0,320,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
17,SUP018,18,High,62.6625,6,1,6,6740532.53,438062.94,80.435897,19,214,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
18,SUP009,19,High,66.8750,5,0,5,8884349.40,0.00,92.647436,8,165,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
19,SUP023,20,Critical,80.2250,4,2,4,4640540.32,4048573.44,35.096154,0,113,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...

In [9]:
# Validate recommendation distribution

print("Recommendation urgency:")
print(
    recommendation_output["recommendation_urgency"]
    .value_counts()
)

print("\nRecommended actions:")
print(
    recommendation_output["recommended_action"]
    .value_counts()
)

Recommendation urgency:
recommendation_urgency
High         11
Immediate     3
Medium        3
Low           3
Name: count, dtype: int64

Recommended actions:
recommended_action
Qualify alternate suppliers for critical parts                         7
Immediate alternate-source qualification for critical parts            3
Routine supplier monitoring                                            3
Develop inventory and supply continuity contingency plan               2
Review procurement concentration and supply continuity options         2
Initiate supplier corrective action and operational recovery review    2
Enhanced supplier monitoring and periodic risk review                  1
Name: count, dtype: int64

In [10]:
# ============================================================
# EXECUTIVE KPI SUMMARY
# ============================================================

kpi_summary = pd.DataFrame({
    "metric": [
        "Total Suppliers Analysed",
        "Critical-Risk Suppliers",
        "High-Risk Suppliers",
        "Total Affected Parts",
        "Total Critical Parts Affected",
        "Total Order Quantity Exposed",
        "Total Procurement Value Exposed",
        "Total Critical Procurement Value Exposed",
        "Total Backorder Exposure",
        "Total Blocked Quantity",
        "Single-Source Parts"
    ],
    
    "value": [
        disruption["supplier_id"].nunique(),
        (disruption["risk_category"] == "Critical").sum(),
        (disruption["risk_category"] == "High").sum(),
        disruption["affected_parts"].sum(),
        disruption["critical_parts_affected"].sum(),
        disruption["total_order_quantity_exposed"].sum(),
        disruption["procurement_value_exposed"].sum(),
        disruption["critical_procurement_value_exposed"].sum(),
        disruption["total_backorder"].sum(),
        disruption["total_blocked_quantity"].sum(),
        disruption["single_source_parts"].sum()
    ]
})

display(kpi_summary)

                                      metric         value
0                   Total Suppliers Analysed  2.000000e+01
1                    Critical-Risk Suppliers  1.000000e+01
2                        High-Risk Suppliers  1.000000e+01
3                       Total Affected Parts  1.470000e+02
4              Total Critical Parts Affected  3.000000e+01
5               Total Order Quantity Exposed  2.294450e+05
6            Total Procurement Value Exposed  3.072879e+08
7   Total Critical Procurement Value Exposed  5.305173e+07
8                   Total Backorder Exposure  4.640000e+02
9                     Total Blocked Quantity  5.890000e+03
10                       Single-Source Parts  1.470000e+02

In [11]:
# ============================================================
# TOP DISRUPTION SCENARIOS
# ============================================================

top_disruption_suppliers = (
    disruption
    .sort_values("disruption_exposure_rank")
    .head(10)
    [
        [
            "disruption_exposure_rank",
            "supplier_id",
            "risk_category",
            "supplier_priority_score",
            "affected_parts",
            "critical_parts_affected",
            "procurement_value_exposed",
            "critical_procurement_value_exposed",
            "average_daily_consumption",
            "total_backorder",
            "total_blocked_quantity"
        ]
    ]
)

display(top_disruption_suppliers)

,disruption_exposure_rank,supplier_id,risk_category,supplier_priority_score,affected_parts,critical_parts_affected,procurement_value_exposed,critical_procurement_value_exposed,average_daily_consumption,total_backorder,total_blocked_quantity
0,1,SUP013,Critical,75.1125,13,3,15020893.01,4216513.82,148.358974,26,396
1,2,SUP036,High,50.4500,8,4,17481523.42,7051419.81,122.134615,23,237
2,3,SUP027,Critical,68.3500,11,0,33795816.58,0.00,187.403846,38,604
3,4,SUP040,High,65.6875,11,1,15768879.02,1662792.86,156.583333,20,390
4,4,SUP008,High,56.3375,6,2,23216159.32,5084413.50,83.641026,216,112
5,6,SUP038,High,64.8500,8,1,31204412.22,559208.63,150.570513,0,274
6,7,SUP014,Critical,71.0125,9,2,13304583.36,1645127.16,122.852564,5,247
7,8,SUP006,High,64.3125,10,0,21451420.65,0.00,149.006410,0,611
8,9,SUP034,High,54.5750,7,2,11953921.12,4706223.50,73.673077,65,158
9,10,SUP033,Critical,77.6250,7,1,16590867.37,801287.69,82.282051,0,763

In [12]:
# ============================================================
# MANAGEMENT ACTION SUMMARY
# ============================================================

management_actions = (
    supplier_recommendations
    [
        [
            "supplier_id",
            "disruption_exposure_rank",
            "risk_category",
            "recommended_action",
            "recommendation_urgency",
            "recommendation_rationale"
        ]
    ]
    .sort_values(
        ["recommendation_urgency", "disruption_exposure_rank"],
        ascending=[True, True]
    )
)

display(management_actions)

,supplier_id,disruption_exposure_rank,risk_category,recommended_action,recommendation_urgency,recommendation_rationale
2,SUP027,3,Critical,Develop inventory and supply continuity contin...,High,High disruption exposure coincides with high d...
3,SUP040,4,High,Develop inventory and supply continuity contin...,High,High disruption exposure coincides with high d...
6,SUP014,7,Critical,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
7,SUP006,8,High,Initiate supplier corrective action and operat...,High,Elevated blocked quantity or backorder exposur...
8,SUP034,9,High,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
9,SUP033,10,Critical,Initiate supplier corrective action and operat...,High,Elevated blocked quantity or backorder exposur...
10,SUP005,11,High,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
11,SUP021,12,Critical,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
13,SUP039,14,Critical,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
15,SUP015,16,Critical,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
19,SUP023,20,Critical,Qualify alternate suppliers for critical parts,High,Multiple critical parts are exposed and the af...
0,SUP013,1,Critical,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
1,SUP036,2,High,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
4,SUP008,4,High,Immediate alternate-source qualification for c...,Immediate,High disruption exposure combined with multipl...
16,SUP026,17,High,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
17,SUP018,18,High,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
18,SUP009,19,High,Routine supplier monitoring,Low,No dominant disruption driver identified relat...
5,SUP038,6,High,Review procurement concentration and supply co...,Medium,High procurement value is exposed if the suppl...
12,SUP024,13,Critical,Review procurement concentration and supply co...,Medium,High procurement value is exposed if the suppl...
14,SUP002,15,Critical,Enhanced supplier monitoring and periodic risk...,Medium,"Supplier is classified as Critical risk, altho..."

In [13]:
# ============================================================
# SAVE DASHBOARD-READY OUTPUTS
# ============================================================

kpi_summary.to_csv(
    "data/processed/executive_kpi_summary.csv",
    index=False
)

top_disruption_suppliers.to_csv(
    "data/processed/top_disruption_suppliers.csv",
    index=False
)

management_actions.to_csv(
    "data/processed/management_actions.csv",
    index=False
)

print("Dashboard-ready files saved successfully:")
print("1. data/processed/executive_kpi_summary.csv")
print("2. data/processed/top_disruption_suppliers.csv")
print("3. data/processed/management_actions.csv")

Dashboard-ready files saved successfully:
1. data/processed/executive_kpi_summary.csv
2. data/processed/top_disruption_suppliers.csv
3. data/processed/management_actions.csv

In [14]:
# Verify saved outputs

import os

files_to_check = [
    "data/processed/executive_kpi_summary.csv",
    "data/processed/top_disruption_suppliers.csv",
    "data/processed/management_actions.csv",
    "data/processed/disruption_scenario_analysis.csv",
    "data/processed/supplier_recommendations.csv"
]

for file in files_to_check:
    print(
        f"{'✓' if os.path.exists(file) else '✗'} {file}"
    )

✓ data/processed/executive_kpi_summary.csv
✓ data/processed/top_disruption_suppliers.csv
✓ data/processed/management_actions.csv
✓ data/processed/disruption_scenario_analysis.csv
✓ data/processed/supplier_recommendations.csv